export const APPRAISAL_STATUS = {
  DRAFT: 'DRAFT',
  REVIEW: 'REVIEW',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

export const USER_ROLES = {
  ADMIN: 'ADMIN',
  LENDER: 'LENDER',
  APPRAISER: 'APPRAISER',
  EMPLOYEE: 'EMPLOYEE'
};

export const DOCUMENT_TYPES = {
  TITLE_DEED: 'TITLE_DEED',
  FLOOR_PLAN: 'FLOOR_PLAN',
  PLAT_MAP: 'PLAT_MAP',
  PROPERTY_PHOTO: 'PROPERTY_PHOTO',
  TAX_RECORD: 'TAX_RECORD',
  OTHER: 'OTHER'
};

export const PROPERTY_TYPES = {
  SINGLE_FAMILY: 'SINGLE_FAMILY',
  CONDO: 'CONDO',
  MULTI_FAMILY: 'MULTI_FAMILY',
  COMMERCIAL: 'COMMERCIAL',
  INDUSTRIAL: 'INDUSTRIAL'
};

export const STATUS_LABELS = {
  [APPRAISAL_STATUS.DRAFT]: 'Draft',
  [APPRAISAL_STATUS.REVIEW]: 'In Review',
  [APPRAISAL_STATUS.COMPLETED]: 'Completed',
  [APPRAISAL_STATUS.CANCELLED]: 'Cancelled'
};

export const STATUS_COLORS = {
  [APPRAISAL_STATUS.DRAFT]: '#2196F3',
  [APPRAISAL_STATUS.REVIEW]: '#FF9800',
  [APPRAISAL_STATUS.COMPLETED]: '#4CAF50',
  [APPRAISAL_STATUS.CANCELLED]: '#f44336'
};

export const DOCUMENT_TYPE_LABELS = {
  [DOCUMENT_TYPES.TITLE_DEED]: 'Title Deed',
  [DOCUMENT_TYPES.FLOOR_PLAN]: 'Floor Plan',
  [DOCUMENT_TYPES.PLAT_MAP]: 'Plat Map',
  [DOCUMENT_TYPES.PROPERTY_PHOTO]: 'Property Photo',
  [DOCUMENT_TYPES.TAX_RECORD]: 'Tax Record',
  [DOCUMENT_TYPES.OTHER]: 'Other'
};

export const PROPERTY_TYPE_LABELS = {
  [PROPERTY_TYPES.SINGLE_FAMILY]: 'Single Family',
  [PROPERTY_TYPES.CONDO]: 'Condo',
  [PROPERTY_TYPES.MULTI_FAMILY]: 'Multi Family',
  [PROPERTY_TYPES.COMMERCIAL]: 'Commercial',
  [PROPERTY_TYPES.INDUSTRIAL]: 'Industrial'
};
